spring:
  datasource:
    url: jdbc:sqlite:/home/khoi/Custom/P-Projects/FbAuthSimulate2/database/data.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
